repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-json
        exclude: (\.jshintrc)
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: end-of-file-fixer
