export const PARAMETERS: {
  [parameter: string]: {
    [option: string]: string;
  };
} = {
  "Emotional prompt words": {
    "postive-mood-low-energy": "Postive mood, low energy",
    "postive-mood-high-energy": "Postive mood, high energy",
    "negative-mood-low-energy": "Negative mood, low energy",
    "negative-mood-high-energy": "Negative mood, high energy",
  },
  "Size-y, structure-y words": {
    "big-and-free": "Big and free",
    "big-and-structured": "Big and structured",
    "small-and-structured": "Small and structured",
    "small-and-free": "Small and free",
  },
  "Looks, vibes, -punks, -waves": {
    "vaporwave-neon-pink-blue": "Vaporwave: neon, pink, blue",
    "post-apocalyptic": "Post-apocalyptic",
    "gothic-fantasy": "Gothic, fantasy",
    "cybernetic-sci-fi": "Cybernetic, sci-fi",
    steampunk: "Steampunk",
    memphis: "Memphis",
    dieselpunk: "Dieselpunk",
    afrofuturism: "Afrofuturism",
    cyberpunk: "Cyberpunk",
    "biopunk-organic": "Biopunk, organic",
  },
  "Camera angles: proximity": {
    "extreme-close-up": "Extreme close-up",
    "close-up": "Close-up",
    "medium-shot": "Medium shot",
    "long-shot": "Long shot",
    "extreme-long-shot": "Extreme long shot",
  },
  "Camera angles: position": {
    "overhead-view": "Overhead view",
    "low-angle": "Low angle",
    "aerial-view": "Aerial view",
    "tilted-frame": "Tilted frame",
    "over-the-shoulder-shot": "Over-the-shoulder shot",
  },
  "Camera settings + lenses": {
    "fast-shutter-speed": "Fast shutter speed",
    "slow-shutter-speed": "Slow shutter speed",
    bokeh: "Bokeh",
    "tilt-shift-photography": "Tilt shift photography",
    "motion-blur": "Motion blur",
    "telephoto-lens": "Telephoto lens",
    "macro-lens-macro-photo": "Macro lens, macro photo",
    "wide-angle-lens-15mm": "Wide angle lens, 15mm",
    "fish-eye-lens": "Fish-eye lens",
    "deep-depth-of-field": "Deep depth of field",
  },
  "Lighting prompts: natural + outdoor": {
    "golden-hour": "Golden hour",
    "blue-hour": "Blue hour",
    midday: "Midday",
    overcast: "Overcast",
    "shadow-silhouette": "shadow & silhouette",
  },
  "Lighting prompts, artificial / indoor": {
    "warm-lighting": "Warm lighting",
    cold: "Cold",
    "flash-photography": "Flash photography",
    "colourful-lighting-defined-colours":
      "Colourful lighting', defined colours",
    "defined-real-light-source": "Defined 'real' light source",
    "high-key-lighting": "High-key lighting",
    "low-key-lighting": "Low-key lighting",
    "backlighting-backlit": "Backlighting, backlit",
    "studio-lighting": "Studio lighting",
    "defined-direction": "Defined direction",
  },
  "Creative film types, stocks & processes": {
    kodachrome: "Kodachrome",
    autochrome: "Autochrome",
    lomography: "Lomography",
    "polaroid-instax": "Polaroid, Instax",
    cameraphone: "Cameraphone",
    cctv: "CCTV",
    "disposable-camera": "Disposable camera",
    daguerrotype: "Daguerrotype",
    "camera-obscura": "Camera obscura",
    "double-exposure": "Double exposure",
  },
  "Creative film types II": {
    cyanotype: "Cyanotype",
    "black-and-white-tri-x-400tx": "Black and white, Tri-X 400TX",
    "redscale-photography": "Redscale photography",
    "infrared-photography": "Infrared photography",
    "bleach-bypass": "Bleach bypass",
    "instagram-hipstamatic-2015": "Instagram, Hipstamatic, 2015",
    "contact-sheet": "Contact sheet",
    "colour-splash": "Colour splash",
    solarised: "Solarised",
    anaglyph: "Anaglyph",
  },
};
